### ISSUE TITLE
Clear routes to most important items

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#10]
- Who we are
- What we do
  - Working groups
  - Projects
  - Local groups
- Get involved / Do Something!

**Comment by smth** [comment]
I think this is somewhat improved in the latest design for the homepage https://github.com/okfn/okfn.org/raw/master/designs/okfn_05_home_02.jpg

**Comment by rufuspollock** [comment]
Agreed. That looks really good. When could that get merged into the site?

**Comment by smth** [comment]
Any time really. I have a working version here http://staging.okfn.org/ so would be easy to switch.

There a few new things new things here:
- The tweaked content.
- The new colour scheme, to make it look less like a default Bootstrap site.
- The banner; the idea is to create the montage dynamically from Flickr, we haven't built that yet though so it is just a single image.

If you are happy, I'll go ahead and make the changes.
