### ISSUE TITLE
Bugs with default theme navbar and ribbon

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#100]
See e.g. http://opendatacommons.org/
- tagline is in white and hardly readable
- ribbon overlays navbar links

@mintcanary - can you take a look

Here's a screenshot http://awesomescreenshot.com/02c1bvsi17

**Comment by smth** [comment]
Tagline fixed.
I'm not seeing that ribbon issue. Did you have it set to something other than 'relative' in the settings?

**Comment by rufuspollock** [comment]
I don't know re relative. I had not touched the config on this for months and just noticed now when I went to the site ...

**Comment by smth** [comment]
Must have been a cache issue then. All seems fine now. Closing issue.
