### ISSUE TITLE
Twitter Plugin

### ISSUE THREAD

**Issue by smth** [okfn/okfn.org#101]
The Twitter plugin (Tweetblender) currently in use on okfn.org (and probably other sites on our blog farm) no longer works (since the retirement of Twitter API v1). It doesn't look like the author intends to update it.

**Comment by smth** [comment]
This is looking like a reasonable replacement to me http://wordpress.org/plugins/jm-last-twit-shortcode/

**Comment by smth** [comment]
To restore feed:
- Activate above plugin
- Add a text widget containing something like: [jmlt count="4" show_twittar="on"]

**Comment by rdonovan** [comment]
@mintcanary can the Tweet Blender plugin be deactivated and removed? It has left some rather large database tables that would be nice to trim.

**Comment by smth** [comment]
I don't see why not.
