### ISSUE TITLE
Smaller sizes of okfnlabs logo in assets.okfn.org

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#104]
e.g. one suitable for header http://okfnlabs.org/ or for http://publicbodies.org (sizing down the big version does not work so well ...)

And while we're at it ;-) could we get a nice square labs logo for use on e.g. https://twitter.com/okfnlabs or for gravatars ...

**Comment by smth** [comment]
http://assets.okfn.org/p/labs/img/logo-flask.png
http://assets.okfn.org/p/labs/img/logo-flask-small.png
http://assets.okfn.org/p/labs/img/logo-flask-large.png
http://assets.okfn.org/p/labs/img/logo-flask-avatar.jpg

**Comment by smth** [comment]
Superseded by #119
