### ISSUE TITLE
Standard blog entry list page does not look right

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#105]
In particular author info is out on its own above the entry.

![latest posts open knowledge foundation blog](https://f.cloud.github.com/assets/180658/703507/e31d3b1a-ddab-11e2-9833-6fd8c44a9059.png)
http://blog.okfn.org/latest

**Comment by rufuspollock** [comment]
@mintcanary assigning to you in the first instance just to take a look - not super urgent!

**Comment by smth** [comment]
This how now been styled like the single post page.

**Comment by rufuspollock** [comment]
I'm just reopening because e.g. this page looks weird: http://blog.openspending.org/2013/06/30/

In particular sidebar is at the bottom of the page and top part does not look great ...

**Comment by smth** [comment]
I think this is a different template, the equivalent would be http://blog.openspending.org/
However, whatever page this is, it is broken. I'll take a look.
