### ISSUE TITLE
Prominent links to Facebook and Twitter

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#11]
At present the top right links in buddypress bar are actually share this buttons **not** links to our Facebook or Twitter account (which is what I expected).
- I would remove these as I don't think that many people just want to share a given page
- I don't think we want these in top bar. I wonder if we could put these instead (with nice icons) in the main navbar (alternatively we can put in the footer)

**Comment by smth** [comment]
Like this? https://github.com/okfn/okfn.org/raw/691cd7cc531aa7fb10c6d84c7e48dba7d3b753db/designs/okfn_05_home_02b.jpg

**Comment by rufuspollock** [comment]
Yes.

**Comment by smth** [comment]
Done
