### ISSUE TITLE
Adopt a size naming convention for standard logos and create those sizes

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#119]
At the moment http://okfn.org/media contains logos in a wide variety of sizes. It would be nice to:
- Have logos in at least 2-3 sizes (large, normal and (possibly) small)
- Adopt a naming convention for those (perhaps -l, -s for large and small ...)

**Comment by rufuspollock** [comment]
@mintcanary something to think about - not immediate. Your thoughts welcome!

**Comment by smth** [comment]
I think this is a good idea, is on my to-do list.

**Comment by smth** [comment]
I have now added dropdowns with three sizes for each logo on http://okfn.org/media/
