### ISSUE TITLE
Settings for for non-staff members

### ISSUE THREAD

**Issue by lauranewman** [okfn/okfn.org#12]
[Not sure if this is the best place for this issue - feel free to move if not.]

The current profile options are confusing for non-staff members who create an OKFN profile via okfn.org/register. 

The most prominent options (under 'Welcome xxxx xxxx') are 'Dashboard' and 'Profile', but users without wp access get an auto response saying they don't have permission to access these areas. Additionally, the page on which they actually can edit their own profile (okfn.org/members/username) is very obscure.

Only one person has complained so far, but I can see why it is confusing. Is there any way we can change this?

**Comment by smth** [comment]
Is this in the sidebar? I guess the plugin isn't smart enough for this. We could remove those options for everyone?

**Comment by lauranewman** [comment]
Yep, in the sidebar. I think removing those options is probably best - I think most staff members get into the Dashboard via wp-admin anyway.

**Comment by smth** [comment]
Done. For future reference, those links can be added and removed via settings.
