### ISSUE TITLE
Problem with JQuery when we login in the Wordpress admin panel

### ISSUE THREAD

**Issue by everton137** [okfn/okfn.org#120]
Here is the message we receive everytime on the admin panel of OKF Wordpress

> blockUI requires jQuery v1.2.3 or later!  You are using v1.10.2

And here is a possible solution

http://wordpress.org/support/topic/wordpress-36-and-jqueryblockui-version-problem-solution

**Comment by smth** [comment]
Looks like the 'sidebar login' plugin was the culprit. Updating it has fixed this issue.

**Comment by everton137** [comment]
Thanks, @mintcanary !
