### ISSUE TITLE
Source files of okfn.org/media/

### ISSUE THREAD

**Issue by everton137** [okfn/okfn.org#122]
Hi, I saw the modifications at http://okfn.org/media/, which looks great, thanks!

Wouldn't be good to have the editable versions of these files as well? (SVG or even proprietary files used to generate the PDF or PNG versions, for instance)

This will help local groups to adapt to their contexts and/or languages.

**Comment by smth** [comment]
Editable versions of logos are all there (as EPSs). Would it be useful to have InDesign packages for the print stuff?

**Comment by everton137** [comment]
@mintcanary , I don't have access to softwares to edit InDesign files, but I've found volunteers in Brazil who can help with that. So, yes, I think it would be really useful!

I didn't know EPS was editable, I thought only the SVG. Thanks!

**Comment by smth** [comment]
Ok, I'll put it on my to-do list.

EPS and SVG are very similar, EPS is probably more editable in some respects, and is more of an industry standard.

**Comment by smth** [comment]
I think this is pretty complete now.
