### ISSUE TITLE
Grainy user images on community.openspending.org

### ISSUE THREAD

**Issue by nmashton** [okfn/okfn.org#123]
We've had problems with mysteriously low-resolution user images on blog posts on [community.openspending.org](http://community.openspending.org) (formerly blog.os.org):
- [http://blog.openspending.org/2013/08/29/new-york-comptroller/](http://blog.openspending.org/2013/08/29/new-york-comptroller/)
- [http://community.openspending.org/2013/09/13/finance-data-standards/](http://community.openspending.org/2013/09/13/finance-data-standards/)

For Marc Joffe's post, this is what we've tried to do to fix it, with no success:
- removing and recreating his account on the platform
- deleting and re-uploading his picture on the OKFN platform
- re-sizing his profile picture to 306x306 and 240x240, re-uploading to the OKFN platform. All steps involved both keeping the crop square box as-is and enlarging it, both to no satisfactory result.

**Comment by smth** [comment]
To fix, either:

```
Ensure users have a Gravatar associated with their email address
or disable large avatars under 'theme options'
```

See https://github.com/okfn/wordpress-theme-okfn/issues/35
