### ISSUE TITLE
Apply standard okfn.org (or even ckan.org) styling to our docs theme

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#124]
docs theme is https://github.com/okfn/sphinx-theme-okfn (currently default old bootstrap ...)

**Comment by smth** [comment]
I'm not too familiar with Sphinx or our docs, but I could probably do this. A few questions:
- Is there anything from the existing theme that needs to be maintained, or could we start from scratch?
- Is there any benefit to including Bootstrap in this? Seems like it might just be needless bloat, we could just build on the default Sphinx theme.
- Does it need to mimic the OKF and/or CKAN sites? A different layout but with consistent branding seems reasonable to me.

**Comment by rufuspollock** [comment]
Will get back to you on this.

**Comment by rufuspollock** [comment]
@mintcanary ok, i think i'd like to keep the bootstrap basis. It makes it easy to do certain things within the theme. Frankly I don't think we need to built off sphinx much (rather we re-incorporate some sphinx specific things we have to on top of bootstrap). Right now we could be very basic - just make it a bit lighter.

I'd suggest mimicking OKF default theme to start with (what would be perfect is that we had a common, central OKF on top of bootstrap css file we link to and then have minimal local mods ...)

**Comment by smth** [comment]
Isn't that what we already have here? http://assets.okfn.org/themes/okfn/

``` html
<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/css/bootstrap.min.css" rel="stylesheet"> <!-- Standard BS -->
<link href="styles.css" rel="stylesheet"> <!-- OKFN Branding -->
<link href="http://assets.okfn.org/themes/bootstrap-responsive.css" rel="stylesheet"> <!-- BS Responsive (edited to omit large desktop styles) -->
<link rel="stylesheet" href="http://assets.okfn.org/themes/okfn/okf-panel.css"/> <!-- OKF Sliding Panel -->
<link rel="stylesheet" href="http://assets.okfn.org/themes/okfn/okf-footer/okf-footer.css"/> <!-- OKF Footer -->
```

**Comment by rufuspollock** [comment]
Yes, we just need to apply that to the sphinx stuff

**Comment by smth** [comment]
OK. Do we know what sites are using this theme? Maybe I could use one for testing..

**Comment by smth** [comment]
I've added the styling here https://github.com/okfn/sphinx-theme-okfn/pull/34
Would be good to be tested by someone who knows more about the "sphinx specific things".

**Comment by rufuspollock** [comment]
FIXED. Plus closing in favour or relevant issue in sphinx theme repo https://github.com/okfn/sphinx-theme-okfn/issues/35
