### ISSUE TITLE
Open Data Introduction Slides

### ISSUE THREAD

**Issue by smth** [okfn/okfn.org#127]
The slideshow which has been embedded here
http://okfn.org/opendata/
seems to be triggering a bug in Firefox, causing the page to jump down upon loading.

This slidedeck looks a bit clumsy here anyway, so one solution would be to remove it and add the content into the page.

**Comment by rufuspollock** [comment]
@mintcanary can we not do this without discussing ... (there is a reason it is a slideshow etc)

**Comment by smth** [comment]
Are you saying:
1. Remove the slidedeck, no need to discuss (but make sure it's still presented as a slideshow)
   or
2. Leave the slidedeck, end of discussion (the page is as intended)
   ?

**Comment by rufuspollock** [comment]
I'm saying leave the slidedeck - if we could fix the bug that would be great ...

**Comment by smth** [comment]
Arguably not a bug: https://bugzilla.mozilla.org/show_bug.cgi?id=632321

That thread also offers work-around to use when embedding such iframes.
