### ISSUE TITLE
Use "featured image" feature of wordpress

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#129]
I'd like to suggest upgrading our home-grown solution with magazine-image to "featured image" https://codex.wordpress.org/Post_Thumbnails

I'd also like to suggest that we start using the same image both for display on front page, for thumbnails and for the default image in the post (we'd insert if user did not ...)

Lastly, but possibly relatedly, i think we should start storing more of our media in our wordpress instances (but perhaps have us back our wordpress media storage onto s3 ... - there are plugins for that!)

@mintcanary

/cc @nickstenning

**Comment by smth** [comment]
Definite +1

This is how it works with our other themes, and storing media in Wordpress instances is what I suggested in my proposal in August.

I can handle the changes to the theme functionality. @nickstenning would you like to look into backing up to s3, or perhaps uploading directly to s3 via Wordpress interface?

To clarify @rgrp, you'd like the image to be inserted at the start of the post (automatically, as opposed to allowing author to do so manually)?

**Comment by everton137** [comment]
Big +1.

This'd be a reliefe from an user point of view. Because of the bug that converting from Visual to HTML to VIsual mode strip HTML tags, hence stripping the <!- magazine.image = IMAGE_URL --> tag, that would facilitate our lifes when we need small adjustments and have to keep adding the featured image everytime.

**Comment by smth** [comment]
First part ready to go here https://github.com/okfn/wordpress-theme-okfn/commit/af0b76c2184eb249e06208398e244bc94a664913

Note: This (or any other changes) cannot be put live at the moment, due to 'IT issues #4173' in Tender.

**Comment by smth** [comment]
This is now live. I have refrained from having the image automatically inserted into the post. It is easy to reuse the Featured Image in the post, via the Wordpress interface, and letting people do so manually will give them greater flexibility.

**Comment by everton137** [comment]
@mintcanary @nickstenning When you do these changes, are all local groups/chapters sites also updated?

**Comment by smth** [comment]
If it's a change to theme (such as this), all sites on our blog farm, using that theme, will get the changes at the same time.

This was the only theme with this particular issue, so (assuming all the group/chapter sites are on our blog farm) every site previously affected, will have been updated.
