### ISSUE TITLE
Carousel images not in git assets repo 

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#16]
I suspect this is because the relevant file has not been pushed to assets.okfn.org git repo ...

**Comment by ghost** [comment]
Seems to work, can I close this?

**Comment by rufuspollock** [comment]
Not yet! I've changed the title to something more meaningful and left it open.

**Comment by teajaymars** [comment]
Going to need info to prove this is duplicable. Have tested before & after deployment on multiple architectures and browsers.

**Comment by rufuspollock** [comment]
Apologies. Had updated title to be clearer but did not save it seems. Have updated now. Note certain carousel _is_ working (it's about the images being in assets -- perhaps not supposed to be?)!

**Comment by teajaymars** [comment]
Is this your local redirect of assets creating issues again? :-)

**Comment by rufuspollock** [comment]
@zephod: The issue is _now_ about the images _not_ being in the **git** repo.

Why is this important? What happens if assets.okfn.org ever gets borked and we need to rebuild. The rule is the file must _either_ be in the git repo or the git repo must contain a script or very clear instructions on how to do the relevant build step (e.g. get this image from flickr and push to assets.okfn.org)

**Comment by teajaymars** [comment]
I just forgot to type `git push`. It's done now.

This is a symptom of the fundamental problem with having two remotes to deploy to. I've been nagging Nick Stenning to setting up our puppet server as the sole remote, which will auto-deploy to S3. Feel free to nag him :-) I don't have [SSH access](https://raw.github.com/zephod/dotfiles/master/id_rsa.pub) to the puppet server so can't do this myself.
