### ISSUE TITLE
Homepage Content

### ISSUE THREAD

**Issue by smth** [okfn/okfn.org#18]
Homepage copy needs some attention. I think it needs too be easier for someone visiting for the first time to understand what we do and what we offer.

For example:
- "Incubate a project" seems like a strange use of language to me, perhaps "Propose a project" would be better.
- "Deploy CKAN" should probably be something like "CKAN, our open source data portal software"

**Comment by noelmas** [comment]
Make font size on homepage larger

**Comment by noelmas** [comment]
Create carousel like ckan.org -- show:
1. OKFest 2. CKAN 3. Open Spending 4. Public Domain Review 5. Open Data Handbook 6. School of Data

**Comment by rufuspollock** [comment]
DUPLICATE. Merging with #3
