### ISSUE TITLE
Create a set of bespoke designs for front page carousel

### ISSUE THREAD

**Issue by noelmas** [okfn/okfn.org#20]
Suggest the following should be covered:
1. OKFest
2. CKAN
3. Open Spending
4. School of Data
5. TEXTUS

**Comment by smth** [comment]
So are these no longer required (see #27)?

**Comment by smth** [comment]
Continued discussion from #3 Here is an example of an OKFest banner with the text formatted as on ckan.org https://raw.github.com/okfn/okfn.org/master/designs/okfn_08_home_02.jpg as opposed to being bespoke per image https://raw.github.com/okfn/okfn.org/master/designs/okfn_08_home_01.jpg Not a huge difference.

Regarding the suggestion from @rgrp to use the ckan layout with the images that are currently in use, what you'd get is something like this https://raw.github.com/okfn/okfn.org/master/designs/okfn_08_home_02b.jpg ie text oddly positioned and illegible. We can obviously make this work by putting a solid colour behind the text, but don't see it being an improvement over what we currently have.

**Comment by rufuspollock** [comment]
There's been real confusion here: I didn't mean overlay the text on the image I meant like ckan.org where image is only 50% of screen and then text is other 50% (on some solid background ...)

**Comment by smth** [comment]
Ok, I see. The confusion comes from the fact that technically the text is overlaid on ckan, but I designed the banners to have nothing going on on the right hand side, much as the OKFest example above. So you want the current photographs, but at a different aspect ratio, so they only fill half the screen?

**Comment by rufuspollock** [comment]
Dependent on #33.

**Comment by noelmas** [comment]
I will comment here on what should be modified immediately on carousel:
- Delete the opening Open Knowledge Foundation slide with people sitting on grass
- Delete Working Group slide
- Delete Open Government Data Camp slide
- Add a slide on the OKFN blog

Copy: The Open Knowledge Blog is the place to keep up-to-date about all the most important happenings related to open data and content across the globe.

Image: Cool screenshot of blog

**Comment by smth** [comment]
All tasks from previous post now done.
