### ISSUE TITLE
List funders ...

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#21]
- Sort out 'supporters' page. 
  - Add extra type: 'Funders'
    - Shuttleworth
    - Open Society Foundation (/ OSI)
    - Omidyar
    - Sloan Foundation
    - Knight
    - ...
- Pull out a selection of funders & collaborators for the footer of the site ...? cf http://pculture.org/

**Comment by smth** [comment]
New footer design: https://github.com/okfn/okfn.org/raw/master/designs/okfn_08_home_01.jpg

**Comment by rufuspollock** [comment]
not sure whether we want this in footer or on say http://okfn.org/support/thanks ...

Possbily both and the nice logos are good.

**Please note** we _must_ contact all funders and get their permission (plus preferred) logos before _any_ deployment.

**Comment by rufuspollock** [comment]
@noelmas we probably need to check with funders re use of logos, can you help lead on this (may just involve pinging relevant people to ask)

**Comment by noelmas** [comment]
Sure - I've got a list now - I'll ping all this afternoon.

**Comment by noelmas** [comment]
Started compiling list https://docs.google.com/spreadsheet/ccc?key=0Al6mO9_3Hr2PdEFvX0ZZem9BVExGZFRPQTJjMHJNRGc#gid=0

**Comment by noelmas** [comment]
Okay, so mock-up of footer looks fantastic. We should implement. We need to hang back on Sloan, OSF and Hewlett some of them ar estill preparing their usage documents. I suggest our initial list then is:

Shuttleworth
Omidyar
NED
Knight

**Comment by smth** [comment]
Does that mean the above list _have_ sent logos and/or usage documents?

**Comment by noelmas** [comment]
The above 4 have approved that we can use their logos on our main site and have no objections to what was proposed

**Comment by smth** [comment]
Those four logos have now been added to the footer.

**Comment by noelmas** [comment]
Do you mean in the mock-up? A couple of the funders who we haven't got confirmation from don't want to be seen to endorse our website content. Please forward any new mock-ups so that I can show them what we plan to do.

**Comment by smth** [comment]
I mean the four approved logos are now on the live site.

**Comment by rufuspollock** [comment]
Great to see this up there but I should say that this does look a bit odd as it stands in the footer. I'm also wondering whether we really want this in the footer as opposed to a dedicated page elsewhere e.g. http://okfn.org/support/thanks (though that isn't perfect as yet ...)

**Comment by noelmas** [comment]
I think it does look slightly odd, but that the implementation could be neatened up. @mintcanary , I know this is vague, but any way of giving is less of "stuck on" feel. Currently looks like a bit of an after thought. The mock-up somehow looked better.

**Comment by smth** [comment]
I don't follow; apart from a larger font size for "Funded by" (and there being less logos), it looks pretty much identical to the mock-up.

**Comment by noelmas** [comment]
Maybe it is size of logos then. I'll hopefully have confirmation of a couple of more shortly, so that we can reduce their size

**Comment by noelmas** [comment]
@mintcanary I now have approval from NED that we can also use their logo - let's put that in and see if footer starts looking better. I have put all logos I have been sent by comms departments in Drop Box - OKF Box / Funder Logos

**Comment by smth** [comment]
The NED logo is already there..

**Comment by noelmas** [comment]
@mintcanary apologies - pre-coffee GitHub issues comment not a good idea! I meant Hewlett logo.

**Comment by smth** [comment]
Ok, that's there too now :)

**Comment by noelmas** [comment]
So looking at the list of funders, which I think is a massive improvement, the ones at the far left are obscured by the OKFN logo. Is there a way of making sure all logos are visible? Perhaps change the shade of the funder logos a bit?

**Comment by noelmas** [comment]
Sloan have confirmed we can use their logo. @mintcanary  I have sent you relevant files

**Comment by smth** [comment]
There is no OKFN logo in the footer.. I think we must be looking at different things here. If you are looking at the footer, and it doest look like the design in my first comment, maybe you are seeing a broken/cached version?

**Comment by noelmas** [comment]
Yes, I just commented on another issue along those lines. I have been looking at a broken cached version! Chrome has now refreshed and I'm seeing the brand new shiny one now! Looks so much better. Very peculiar though as things like new logos were appearing but with old theme in the background.

**Comment by smth** [comment]
Sloan logo added.
