### ISSUE TITLE
Collaborators page

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#22]
Rename 'partners' to 'collaborators'.
- Grab extra collaborators from list: https://docs.google.com/spreadsheet/ccc?key=0AnCtSdb7ZFJ3dDFuQnAtTTl0Ul9oX3k2NVBYWnVOSnc#gid=0

**Comment by smth** [comment]
Does this refer to okfn.org/partners? Is it linked to from anywhere? Should it be?

**Comment by rufuspollock** [comment]
WONTFIX for the present IMO.
