### ISSUE TITLE
Projects drop-down in main menu should linke to main projects directly

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#23]
- E.g. at least "flagship" projects should be in there.
- Also move propose project to bottom (@mintcanary any way to get separators?)
- See also #6

**Comment by smth** [comment]
I don't think there is a way at the moment to add separators, but I have just added styling for a third level of menu items, so that could be another solution to the problem..

**Comment by smth** [comment]
Flagship projects now in menu.
