### ISSUE TITLE
Support / donate pages / site

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#24]
This is a discussion place for better donate / support pages.

**Comment by smth** [comment]
The "participate" link on the Support page is broken.

**Comment by smth** [comment]
This discussion doesn't seem to be happening.. Is it worth me designing the content we already have?

**Comment by rufuspollock** [comment]
No, this needs to a conversation with Sam Leon and others. Aim should probably be to schedule a phone call in next couple of weeks (once Sam is back).

**Comment by noelmas** [comment]
I will be outlining changes that need to be made and writing up all content for the website in the following Google Doc:

http://bit.ly/RmImFb

This will include new content, copy and tweaks for Supporters and Donate page
