### ISSUE TITLE
Banner space for announcing bits of news (e.g. OKFestival)

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#27]

**Comment by smth** [comment]
I think, as we discussed, the current banner space should be used for this: https://github.com/okfn/okfn.org/raw/master/designs/okfn_07_home_02.jpg

**Comment by smth** [comment]
If we go ahead with this, proposed banners to create are in issue #20

**Comment by rufuspollock** [comment]
I can't see anything different in that diagram from the standard carousel. I'm thinking of something non-pictorial like the old tag line ...

**Comment by smth** [comment]
I thought we agreed that the carousel would be used for this..

**Comment by rufuspollock** [comment]
Not sure we did but if we did apologize because that wasn't what I meant.

First off #28 is clearly a duplicate of this so I'm going to close in favour of this. Second I think we do just want to have something like the old tag line that we can set (and unset).

I'd also say this wasn't super important compared to getting front page sorted out.

**Comment by smth** [comment]
The problem with having something that can switch on and off, where the old tag-line was, is that it could potentially break the layout of some pages. I was thinking about making something like this https://github.com/okfn/okfn.org/raw/master/designs/corner-ribbon_01.jpg but it would obviously be limited in characters.

**Comment by rufuspollock** [comment]
Suggest we try this out on science.okfn.org and okfn.org front page

**Comment by rufuspollock** [comment]
Also to clarify I think I am now +1 on your original design though probably for a different purpose from originally envisaged in this ticket: namely we now use this as a RSS feed news ticket below the carousel whereas original idea was more about being able to put permanent (unchanging) banner for important news like "Come to OKFestival"

**Comment by smth** [comment]
I have added the ribbon to okfn.org as suggested above.
I think the RSS feed may now be slightly redundant on the homepage, as we have a feed from our blog on there.

**Comment by noelmas** [comment]
Agreed
