### ISSUE TITLE
Ability to set a flash message

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#28]
Imagine this going where old tag line went. Used to advertise important things e.g.
- OKFestival
- Jobs
- ...

**Comment by smth** [comment]
I think my answer to #27 also applies here. Do you want space for this on other pages too?

**Comment by rufuspollock** [comment]
I think it might be nice to do site wide (like old tag line ...) as a default.

If it were just one page I think we could just do with html and css in a given page ...

**Comment by smth** [comment]
I was thinking smaller versions of the homepage banners, in the sidebar.

**Comment by rufuspollock** [comment]
DUPLICATE of #27.
