### ISSUE TITLE
Not clear how to log in as a community member

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#29]
Now that we have removed buddypress bar and sidebar for login not clear how to login to the site. Suggestions:
- Have a 'login' link in the footer so if people do search they find it
- Add prominent login stuff to, say, http://okfn.org/community/ web page and link prominently to community page ... (this raises wider question of improving community page)

In some ways this raises wider questions:
- Where should the community site be located - it could be at community.okfn.org or similar
### why?

We still need users to login to join and create groups or update their profile.

**Comment by smth** [comment]
Login form now on http://okfn.org/community/ (when not logged in), linked to from footer.
