### ISSUE TITLE
Better front page with more content

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#3]
- Fix the carousel images to be better esp change the default one to OKCon or similar ...
- Add content below carousel ...
  - Small well style items with links
  - Latest activity as per okfnlabs.org ...
### Content (moved from #18)

Homepage copy needs some attention. I think it needs too be easier for someone visiting for the first time to understand what we do and what we offer.

For example:
- "Incubate a project" seems like a strange use of language to me, perhaps "Propose a project" would be better.
- "Deploy CKAN" should probably be something like "CKAN, our open source data portal software"

RP: I think we also need to have more content below. Suggest we excerpt a few specific things from that set of links below carousel. My suggestions would be:
- Get involved (section on how to join in, that volunteers do lots of our stuff etc)
- Highlight a few projects -- could just copy and paste almost from the first section of the projects page
- Highlight donate / support ...

I also think it is really important we have a simple one-line tag-line style definition of what we do on the front page ...
### References
- http://pculture.org/

**Comment by ghost** [comment]
First two are fixed, only the latest activity box remains

**Comment by smth** [comment]
I plan to add an RSS feed from http://planet.okfn.org/feed to the homepage, hopefully this will meet that demand. I have this working locally, but still need to style it.

**Comment by smth** [comment]
This is what I have in mind for latest activity: https://github.com/okfn/okfn.org/raw/master/designs/okfn_07_home_03.jpg

**Comment by rufuspollock** [comment]
I really think the side-by-side as per CKAN is better as discussed on that day :-) Having some explanatory text works and that latest version still suffers from the fact that the text is basically hidden. So I'm a major +1 on the half and half approach of ckan.org

**Comment by rufuspollock** [comment]
Also we haven't addressed further content issue but that's probably for later (and doesn't need to be designed) - see #18.

**Comment by smth** [comment]
The first comment is presumably regarding the banner. Text doesn't have to be hidden, that's more down to how it is implemented. I think we should agree what we want before worrying about how it will work. Personally I think it would be nice to have the freedom to put the wherever we like, but you keen to have the text always be 50% from the left?

I thought the further content issue had been resolved.. If there is more to go on there, it probably will need to be designed.

I was looking for feedback to the RSS ticker (black bar under the banner) in this thread :)

**Comment by rufuspollock** [comment]
OK: I've merged #18 with this.

Re rss ticker: I'm not absolutely sure. Can we park this while we sort out the actual layout of front page and then come back (minor aside: suggest new items like that go in a separate issue to make discuss easier).

**Comment by smth** [comment]
What needs to be laid out here? Is there additional content to go in?

The RSS ticker idea was in direct response to "Latest activity as per okfnlabs.org" in the original post, the (I thought) one remaining issue in this thread.

**Comment by teajaymars** [comment]
It's impossible to track what's going on here. If five things need non-trivial changes then create five separate tickets for discussion. For example, I thought I'd solved _"Fix the carousel images to be better esp change the default one to OKCon or similar ..."_ by writing a new carousel plugin and putting an OKCon image on the front of it.

All that remains is the content below the banner -- this does need work, somebody needs to write that content though.

**Comment by smth** [comment]
Agreed, additional discussion for the banner continued here #20 Additional discussion for the RSS/latest activity continued here #37

**Comment by rufuspollock** [comment]
@zephod @mintcanary I agree re this ticket. It started out as a discussion ticket and I think we probably should not have tried to start work without resolving what actually needs to be done (@mintcanary is just so damn efficient ;-) ). 

@mintcanary suggestion for the future is that if there is still unresolved X thinks Y, Z thinks A in the main body of the ticket we hold off until resolved.

**Comment by smth** [comment]
Mockup from @noelmas http://twitpic.com/aom7mz

**Comment by smth** [comment]
In response to the layout above: https://raw.github.com/okfn/okfn.org/master/designs/okfn_08_home_05.jpg
In addition, I have added an intro to OKFN, to make it flow a bit better and to address #45
I'm not sure about the four "buzz terms" at the bottom (discussion here: #40)

**Comment by noelmas** [comment]
Hi Sam. I think this is excellent. I'm going to get some second opinions on the buzz items -  I actually think they add something important to the front page.

One issue: We need to distinguish between those boxes that are being pulled in from the blog and those that are static (What is Open Data? and Introduction to OKFN)...

Personally I think we should replace the Introduction to OKFN with a box for "Support Our Work" with a picture of OKFN merch... @rgrp - how essential is it that we have a link to the intro slide deck from the main page?

**Comment by smth** [comment]
For what purpose do we need to distinguish between the blog and static content?

We could always remove one blog item and have both intro and support? If we do link to the intro page, I suggest we remove the slide and recreate it in html.

**Comment by noelmas** [comment]
We should distinguish because "Featured" posts will sometimes be guest blog posts that don't entirely reflect the view of the OKFN on a particular issues. We therefore need to make it clear that this is a news or blog stream in some way.

I think we should have more than one blog item.

I propose that the Intro to the Open Knowledge Foundation is linked to via a banner much like you created for Shuttleworth that reads "Take the introductory tour of the Open Knowledge Foundation"... @rgrp - would be happy with this?

I would say for now link to the slide deck and create a low priority issue to turn that into HTML

**Comment by smth** [comment]
Regarding the blog posts; we could do this https://raw.github.com/okfn/okfn.org/master/designs/okfn_08_home_06.jpg

**Comment by teajaymars** [comment]
Chiming in:

Shiny.

**Comment by noelmas** [comment]
Getting there, but still not quite right - "From our blog" feels like an after thought.

I feel that it will be difficult to do this with these four items all aligned in the same way. Two of them could be smaller than the others or stacked vertically for instance.

Can we mock-up another solution?

**Comment by smth** [comment]
How about this? https://raw.github.com/okfn/okfn.org/master/designs/okfn_08_home_07.jpg

Baring in mind we might want this up quite quickly, I've let ease of building dictate this slightly.. having the blog posts at the very end of the page would require less work.

**Comment by noelmas** [comment]
This looks _a lot_ better. I really like the way the Shape the Knowledge Society. thing is now sandwiched.

As we're now going to have a quote from "Introducing the Open Knowledge Foundation" page. We should drop the strap line at the top (sorry to say) as it's now effectively duplicating something below.

If we finalise version 1 of "What is open data?" when could this be implemented? Are there currently other blockers?

**Comment by noelmas** [comment]
We have also now agreed on slightly different wording for the Shape the Knowledge Society etc buttons. Please change to:

Reform the knowledge society
Protect the digital commons
Free and open access
Community driven

**Comment by smth** [comment]
I did have one eye on dropping the strapline from the top to be honest.

The only blocker is the text really, but I could probably put something together to fit in there if need be. Could probably get this one implemented tomorrow. Should the open data page be revamped before it is linked to though?

**Comment by noelmas** [comment]
I can finalise first version of open data page this evening (we will inevitably need to iterate) which should then be used to refresh the open data page. What is the other text we need?

**Comment by smth** [comment]
An appropriate amount of text to replace the' lorem ipsum' in that last mockup.

**Comment by noelmas** [comment]
Got it - so if someone clicks on it it will go through to @rgrp 's slide deck, right? I'll write something now and post here.

**Comment by smth** [comment]
Yes, that's the idea, with view to improving that page in future.

**Comment by noelmas** [comment]
Left side (with bolding):

The Open Knowledge Foundation is dedicated to promoting the **creation**, **sharing** and **application of Open Knowledge** in the **Digital Age**.

We believe that an **open commons of information** together with the **tools and communities to utilise it** is central to **improving our governance, research, economy and culture.**

Right side:

Same as mock up minus "content and data" and "information" instead of knowledge"

Should read:

"We build technology and communities to create, share and use open information that everyone can use, share and build on."

---

Also, the title in mockup is missing a "the"

---

Will that fit?

**Comment by smth** [comment]
Thanks for this. That heading will probably have to span two lines, shouldn't be a problem though.

I have just realised there is another blocker on this, in terms of the blog posts; the dev work discussed in #44 (I was forgetting that the blog is on a separate website)

**Comment by smth** [comment]
This is what I have now https://raw.github.com/okfn/okfn.org/master/designs/okfn_08_home_07_text.jpg

**Comment by smth** [comment]
The above is now live.

**Comment by noelmas** [comment]
Great, shouldn't the second column beneath "Introducing the Open Knowledge Foundation have larger text"?

**Comment by smth** [comment]
It does have, the image above is a screenshot. You must be seeing a cached stylesheet.
