### ISSUE TITLE
Replace "[...]" with "..." in the RSS Feed

### ISSUE THREAD

**Issue by vndimitrova** [okfn/okfn.org#30]
Replace "[...]" with "..." in the RSS Feed.

Other options to make the Feed nicer?

**Comment by smth** [comment]
To clarify, this is an issue of what is being output from the Wordpress blog feed (not how it is presented). WP adds [...] to the end of its excerpts. Not sure at the moment how easily this can be changed.

**Comment by smth** [comment]
Hi Velichka

I have just added a new template to the OKF wordpress theme, which you might want to try using for the Open Economics homepage. It's called 'Homepage', it will add the latest three blog posts to the bottom of the page, and supports images (in the same way the Magazine template does). If you have any problems with it, report them here https://github.com/okfn/wordpress-theme-okfn/issues

**Comment by vndimitrova** [comment]
Thanks, Sam, this looks really nice, can we also have the sidebar for the Home Theme?

**Comment by smth** [comment]
No, not at the moment.
Another new option is to use this ticker style RSS feed http://staging.okfn.org/
