### ISSUE TITLE
okfn.org carousel like ckan.org (split page with text on RHS)

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#33]
As per discussion on the site sprint day think this work better and convey more information more effectively ...

May require new bespoke images for carousel - see #20 (may want simply to merge #20 with this issue)

Do we want call to action buttons below on RHS as for CKAN.org? Yes, suggest:
- Get involved => get-involved
- See our project => projects
- Get our help => services

**Comment by rufuspollock** [comment]
First pass from @mintcanary https://raw.github.com/okfn/okfn.org/master/designs/okfn_08_home_02.jpg

**Comment by rufuspollock** [comment]
Can we have more like ckan.org - ie. text and image in 2 separate columns

**Comment by smth** [comment]
Second pass, much more like ckan.org https://raw.github.com/okfn/okfn.org/master/designs/okfn_08_home_04.jpg

**Comment by rufuspollock** [comment]
@mintcanary really like that

**Comment by smth** [comment]
Deployed.

**Comment by rufuspollock** [comment]
No call to action buttons? Do we want to leave this for the present?

**Comment by smth** [comment]
I'm happy to put some in. Do you still want them to be the same as the links below; "What We Do", "Get Involved", "How We Can Help"?

**Comment by noelmas** [comment]
Call to action buttons - Sam Smith to mock-up:
- What is Open Data? (link to Open Data page currently being drafted)
- Join the Community (link to community page that needs to be created that goes off to local groups, working groups, volunteer etc)
- Our Activities (goes off to activities page that needs to be created that leads off to Projects, Working Groups, Local Groups)
- Use our Services (goes direct to services site)

Note: these should not have any menu options. They will go straight through to a page which if necessary will then give options of further destinations.

**Comment by noelmas** [comment]
We should try to get above call to action buttons on the carousel in a similar way to CKAN.org. This would then allow us to feature the four boxes discussed in #40 to go below carousel

**Comment by smth** [comment]
For the reason of space, could we combine actions two and three (and create one new page containing the combined contents of the above suggestions)?

**Comment by noelmas** [comment]
I feel we need at least four calls to action. These need only be buttons that have what is in inverted commas above. Merging two and three wouldn't do as they respond to distinct user stories.

On another a note, while we change overall design of carousel. Can we stop text and image from overlapping on current version?

**Comment by smth** [comment]
Where is the text overlapping?

**Comment by noelmas** [comment]
Not sure if I'm having some very bizarre caching issues, but the text was overlapping until today. The design on the website (having just refreshed my chrome browser settings) is displaying a much improved okfn.org with CKAN style carousel and much lighter background. Looking MUCH better. There is no more overlap.

**Comment by noelmas** [comment]
Could we try and implement new call to action buttons in the next couple of days (as above):

What is Open Data? (link to Open Data page currently being drafted)
Join the Community (link to community page that needs to be created that goes off to local groups, working groups, volunteer etc)
Our Activities (goes off to activities page that needs to be created that leads off to Projects, Working Groups, Local Groups)
Use our Services (goes direct to services site)

These buttons should just be small like CKAN carousel buttons "Take Tour" etc and will effectively replace the three boxes we have below the carousel now.

It may be quicker for us to speak on Skype about this, ping me if needed.

**Comment by smth** [comment]
Yes, sounds like you have been experiencing the same caching problems that others have been of late (including myself). I'm glad we are seeing the same thing now.

Yes, should be able to get that done in the next couple of days. They will probably need to be slightly smaller than the CKAN buttons, due to the amount of text that needs to fit in.

**Comment by smth** [comment]
This is how they will look https://raw.github.com/okfn/okfn.org/master/designs/buttons.jpg

Personally, I think it's too many calls to action.

**Comment by noelmas** [comment]
This looks good but I agree, it's not an ideal number.

For now, then, let's drop "What is Open Data?" and find some other way to include a link to that on the front page. Can you re-mock-up with only 3?

**Comment by noelmas** [comment]
So just to recap - this is a very crude mock- up of how this could all come together. Second row of buttons at the bottom would be where those four slogans go from #40.

http://twitpic.com/aom7mz

**Comment by smth** [comment]
https://raw.github.com/okfn/okfn.org/master/designs/buttons2.jpg

**Comment by noelmas** [comment]
Great. Let's implement.

**Comment by smth** [comment]
Ok, buttons are now live. I have created an Activities page, but not linked to it as it needs content.
