### ISSUE TITLE
Dedicated page for OKFN slides / talks

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#35]
Central place to showcase okfn slidedecks / presentations / talks ...

Replace (?) http://wiki.okfn.org/Presentations
### Content

Question: is it just slides or also video etc?

Links out to our slideshare account, vimeo account (specific tag talks?), google docs folder
### Naming

http://okfn.org/talks/ or http://okfn.org/slides or http://okfn.org/presentations

RP: i'd vote for http://okfn.org/talks/ I think

**Comment by noelmas** [comment]
http://okfn.org/talks works for me. I'd be keen to get a solid tagging system for slideshare and vimeo. Ideally we'd want to embed videos and slides from those places to avoid constantly having to update this page... @mintcanary do you know of any plug-ins that allow you to embed your viemo ro slideshare streams in Word Press blogs?

**Comment by smth** [comment]
I can't say I've ever looked into it, but it those sites offer such a feed then I'm sure it wouldn't be too difficult to make it happen.

**Comment by smth** [comment]
In regards to the content question, I wonder if it should be just videos, and not slides. Slides by themselves (without someone talking over them) probably are of little interest. If there is some exceptional content in the slides, I suggest it should be put on the site in its own right, that way it is accessible, discoverable, editable etc.

**Comment by noelmas** [comment]
I agree with you Sam. If there is something we really want to be conveyed on the website, we should put this on a webpage - it will tend to look better.

**Comment by rufuspollock** [comment]
Hmm. There are 2 things here. A showcase and somewhere for us to list (not necessarily all but quite a few) of our slides. Could this page not highlight a few at the top and then allow for listing further down.

**Comment by noelmas** [comment]
Inline with what we were discussing previously. What user story is this going to respond to? We have a slide share account for people who know us and want to see recent talks. But what you seem to want Rufus is a page that can deepen someone's understanding of the OKFN and it's work. In my eyes we should endeavour to do this with dedicated pages supporting this with videos and presentations where necessary (see for instance the proposal for the Open Data page). I'm not convinced having a general talks page is helpful. I do like the idea of embedding our Vimeo feeds somewhere on the website though... Could even be something for the front page once we've stablised carousel and call to action.

**Comment by rufuspollock** [comment]
Bump! I'm going to start putting some stuff up - I _do_ think that having somewhere for the present to put our main talks etc is useful.

**Comment by smth** [comment]
What action would you like taken here @rgrp ?

**Comment by rufuspollock** [comment]
I've started a listify spreadsheet: https://docs.google.com/spreadsheet/ccc?key=0Aon3JiuouxLUdE1SM0NEWTJHMzAwVDVZVVFWNUc3UEE

**Comment by smth** [comment]
Is the plan to put each set of slides in a blog post? If so, having a category for slides could be the answer here.

**Comment by stefanw** [comment]
+1 for `/talks`. We certainly want to put up additional material beyond slides like recordings, maybe related resources, links etc.

**Comment by rufuspollock** [comment]
http://okfn.org/talks is operational - atm it is just a listify embed but we can improve on this as we go along.
