### ISSUE TITLE
Overhaul http://okfn.org/media/ to be central jumping off place for search for okfn.org media materials

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#36]
- Instructions re assets repo and assets.okfn.org
- Subsections with specific links / images for particular projects
  - okfn
  - ckan
  - datahub
  - OpenSpending
  - All major projects listed on http://okfn.org/projects/
  - OKFestival logo
- Other material
  - OKF Poster
  - OKF banner

**Comment by smth** [comment]
Are these to be instructions on how to find stuff on assets.okfn.org? That repo is a bit of a mess, do we need to subject anyone to that?

**Comment by rufuspollock** [comment]
In the first instance I'd just create sections for the major projects and display the relevant logos -- it wouldn't take long. (Sort of like what we have there in a very limited way right now)

**Comment by smth** [comment]
Ok, the above have been added. A couple of the links will be broken until S3 is next updated.
