### ISSUE TITLE
Develop RSS-Based simple banner for insertion in site front pages

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#37]
Idea is to have a simple plugin (use existing) that we style so that it looks like a banner below e.g. the carousel / hero section on front page of relevant sites.
- Example site: http://science.okfn.org/

**Comment by smth** [comment]
I've added my RSS ticker to http://staging.okfn.org/

This can be added like so: [rss feed="http://planet.okfn.org/feed" type="ticker"]

Note: This is part of the theme (not a plugin), this is because it is dependant on Bootstrap (which is also part of the theme).
