### ISSUE TITLE
[super] Site UX and Information Architecture

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#38]

**Comment by noelmas** [comment]
Being drafted on Google Doc:

https://docs.google.com/document/d/1PUtZVuSUoylcM_7cw1SO09CFjtv7MbManGfzLGNTl84/edit

**Comment by rufuspollock** [comment]
@noelmas @mintcanary Should we close this as now either fixed or out of date?

**Comment by smth** [comment]
I'm not entirely sure what this issue is, so I'll leave it up to you guys.

**Comment by rufuspollock** [comment]
FIXED or now INVALID.
