### ISSUE TITLE
okfn.org family of websites should interlink more

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#4]
Use wordpress link options (can one auto-import)?

Set of example links:
- http://okfn.org/
- http://okfn.org/wg/
- http://okfn.org/projects
- http://datahub.io/
- http://ckan.org/
- http://openspending.org/
- http://pybossa.com/
- http://textusproject.com/
- http://opengovernmentdata.org/
- http://opendefinition.org/

**Comment by rufuspollock** [comment]
@samleon this is probably for Joris but he is not yet on github so I couldn't assign him!

**Comment by ghost** [comment]
Assigned myself

**Comment by ghost** [comment]
On every (relevant) webpage is now a footer which links to other related projects

**Comment by rufuspollock** [comment]
@jpekel not quite sure i understand what has happened here. Do we now have these links in a footer widget on every site?
