### ISSUE TITLE
Create set of four boxes that indicate what we are trying to achieve

### ISSUE THREAD

**Issue by noelmas** [okfn/okfn.org#40]
Inspired by:

http://www.soros.org/

The four boxes "Improve Lives" "Foster Change" etc below main carousel.

For now I suggest we just use the following four terms without unpacking them:
- Shape the Knowledge Society.
- Free and open access.
- Foster innovation and insight.  
- Community based.

@mintcanary would be good to get your opinion on where such a series of buzz terms should reside - above or below the carousel etc?

**Comment by smth** [comment]
If this is going to be the entire content for the page, perhaps we should elaborate on each of the headings with a paragraph of text?

**Comment by noelmas** [comment]
My idea is to have these boxes just below the carousel, they're just very bold text to highlight what we do in a slightly more concrete manner a bit like http://www.soros.org/.

**Comment by noelmas** [comment]
Also in #3 - wording should now be:

Reform the knowledge society
Protect the digital commons
Free and open access
Community driven

**Comment by smth** [comment]
Done.
