### ISSUE TITLE
Re-instate a prominent strap line at top

### ISSUE THREAD

**Issue by noelmas** [okfn/okfn.org#41]
Strap-line should be:

"We build technology and communities to create, share and use open information."

Strap-line should appear at the top of the page

**Comment by smth** [comment]
Done.

**Comment by noelmas** [comment]
Great, I like the banner style. We're trying the new strap line that @rgrp  has created see above. Thinking know that it should use the continuous tense. So please change to:

"Building technology and communities to create, share and use open information."

Also, is there any way of making it stand out more? Using a bolder version of the font or maybe italics. Currently the carousel seems sit slightly too close to it IMO

**Comment by smth** [comment]
Font emboldened. Padding increased.
