### ISSUE TITLE
Show recent featured posts from our blog

### ISSUE THREAD

**Issue by noelmas** [okfn/okfn.org#44]
Pull in title and thumbnail of 2 of our most recent "Featured" posts. This should go below the 4 boxes discussed in #40 not disimilar to "Featured Work" section on http://www.soros.org/.

We should call this section "From our blog"

**Comment by smth** [comment]
If the blog was part of the OKFN site, this would be straight forward, the functionality to show three blog post previews is already in place (used here http://linkedup-project.org/). As the blog is on a separate domain, I don't think this method will work, and so we'd have to use the RSS feed. The problem with this is that Wordpress doesn't include an image in the feed.

@zephod Would be good to get a developers opinion.

**Comment by teajaymars** [comment]
Can you get an RSS feed for just `category=featured`?

If so, then I guess you're AJAXing it in with Javascript? I can write an extra bit of JS which extracts the image into an `<img>` tag if you require.

**Comment by smth** [comment]
Looks like you can get a feed for one category http://blog.okfn.org/category/featured/feed/

Docs here http://codex.wordpress.org/WordPress_Feeds

**Comment by teajaymars** [comment]
So how do you embed the feed into the other page? Some kind of Javascript
widget?

**Comment by smth** [comment]
https://github.com/okfn/wordpress-theme-okfn/blob/master/shortcodes.php#L236

**Comment by noelmas** [comment]
@zephod can we bump this dev work up on priority? Front page is looking great with _much_ better content. If we could get blog posts displaying before OKFest traffic really hots up, it would be fantastic

**Comment by teajaymars** [comment]
Done! With thanks to http://wordpress.stackexchange.com/questions/33779/how-to-query-blogs-posts-of-wordpress-sub-domain.

See: http://okfn.org

**Comment by noelmas** [comment]
@zephod  Excellent. Can we also get a neat little line above that says "From our blog"

**Comment by teajaymars** [comment]
_points_ -> @mintcanary

**Comment by smth** [comment]
Haha I'm on it.

**Comment by smth** [comment]
Done (and posts styled).
