### ISSUE TITLE
Link / feature okfn.org/intro more prominently (?)

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#45]
http://okfn.org/intro is a slide deck intro to the OKFN. I use it extensively and its often the default link I share. If we are trying to do a better about/intro page for the OKFN this could be a useful resource (or one could reuse the concepts while not using the slides).

This is a RFC and flagging up exercise rather than an immediate suggestion for action :-)

**Comment by noelmas** [comment]
Can you give more detail?

**Comment by rufuspollock** [comment]
@noelmas done (see description)

**Comment by smth** [comment]
Now linked from homepage.
