### ISSUE TITLE
Footer menu

### ISSUE THREAD

**Issue by noelmas** [okfn/okfn.org#46]
Delete from Footer menu:
- Login
- Contact our team
- Media
- About Us

All links are elsewhere and Footer looks too big. 

Also suggest deleting Twitter, Facebook, Flattr links until we find a better place to have them. Currently they detract from the look and feel of the site.

**Comment by smth** [comment]
Just double checking the removal of links; the login link was only requested to be added recently #29 and I can't see a link to media anywhere else..

I have put the Facebook and Twitter back in the header, now there is room again. I've disabled the Flattr button.

**Comment by noelmas** [comment]
Hi Sam - Facebook and Twitter looks much better now. You may be right that there is no link to media. I'm just concerned about the proliferation of menus and that the menu as it is is really spoiling the footer. As this is not urgent, for now, let's just delete "Contact our team" and "About Us"

**Comment by smth** [comment]
Done.
