### ISSUE TITLE
Take Out Notebook Posts from Activity Monitor

### ISSUE THREAD

**Issue by noelmas** [okfn/okfn.org#49]
There has been some recent discussion that Notebook posts should be made private. We are currently looking for a solution for this.

Pending that can we take out Notebook posts from the activity monitor. If I went to okfn.org as a new visitor I would not be interested in seeing these posts and be put off by that being the most recent update from around our network.

Apologies if this is the wrong place to post such an issue.

**Comment by teajaymars** [comment]
This was fixed after today's Wolfpack call where the feed was removed from planet.okfn.org.
