### ISSUE TITLE
Populate activities page

### ISSUE THREAD

**Issue by noelmas** [okfn/okfn.org#50]
The activities page on the OKFN website should be very simple. It should have 4 large buttons with a small amount of text within the explaining each activity. I can mock-up some ideas for how this should look, but as you have a better eye than me I'd suggest you put forward a mock up first.

Content:

Projects > http://okfn.org/projects/

We play home to a wide variety of projects from large scale open data infrastructure projects to online journals showcasing the best of our digitised cultural heritage.

Working Groups > http://okfn.org/wg/

Our Working Groups are groups of interested individuals who meet virtually and in-person to focus on a particular area of open knowledge such as open government data or open scientific research.

Regional Groups & Chapters > http://okfn.org/chapters/

There are Open Knowledge Foundation regional groups and chapters all around the world. See if there is one in your local area, if not, why not start your own up! 

Get Involved > http://okfn.org/community/get-involved/

The Open Knowledge Foundation is a volunteer based organisation and there are plenty of ways to get involved.

**Comment by smth** [comment]
I've gone ahead and added that content, following the format we already have on other pages http://okfn.org/activities/

**Comment by smth** [comment]
In response to the suggestion of making the links full width and adding icons, how about this? https://raw.github.com/okfn/okfn.org/master/designs/okfn_08_activities_01.jpg

**Comment by noelmas** [comment]
Thoroughly excellent! Let's this up on the site! :)

**Comment by smth** [comment]
Done.
