### ISSUE TITLE
Add pop up box to ask for sign up to OKFN mailing list

### ISSUE THREAD

**Issue by noelmas** [okfn/okfn.org#52]
We are now going to be using Mail Chimp to run our main mailing list to replace OKFN Announce.

We will be using following sign up page:

http://eepurl.com/hhyMU

**Comment by smth** [comment]
Is this to replace the form that is currently at the top of the sidebar? If so, why not directly replace it rather than create a popup?

**Comment by noelmas** [comment]
The Public Domain Review has had a of success with pop up requests to sign up for mailing list. I suggest we try it out. Either way we need to start using Mail Chimp as a matter of urgency.

**Comment by smth** [comment]
Ok. So are you talking about one that automatically pops up when you load the page (just had a look at PDR and couldn't find a pop up)?

**Comment by noelmas** [comment]
Yes, this is an issue Adam Green (don't know if he has a Github user name) has repeatedly raised with Sysadmin. The plug-in he was using has broken and no one has installed a new one. It would be great if we could get the correct plug in installed so that the PDR could use this too. PDR had a lot of extra sign-ups when they had this.

**Comment by smth** [comment]
Had a quick search, this one sounds quite good http://wordpress.org/extend/plugins/wordpress-popup/

**Comment by noelmas** [comment]
Looks good sir! Shall we give it a go?

**Comment by smth** [comment]
It seems that is the plugin being used on PDR, it also appears to be working (the popup was inactive, after activating it works).

So we could go ahead and implement this on okfn.org, I have my reservations though, to me these popups are _the_ most annoying thing on the internet (and I always close them without looking at what's inside them).

Maybe we could think of alternative methods? A slightly less annoying variation, for example, are the popups that only appear when you scroll to the bottom of the page..

**Comment by smth** [comment]
In the meantime, we could replace the current sidebar form with a MailChimp one using this http://wordpress.org/extend/plugins/mailchimp/

If you want me to do this I'll need the MailChimp API Key

**Comment by noelmas** [comment]
Stalling on pop up implementation so now on new issue #66 - simple sign up box

**Comment by smth** [comment]
Closing for now.
