### ISSUE TITLE
Improved events section

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#53]
- top of events page has some nice box sections with description and links to key items
  - OKFestival and OKCon (http://okfn.org/okcon/ etc etc)
- Hackdays and data days (and datathons?)
  - /events/hackdays-and-datadays/ - brief description, list of previous events, latest events
    - We can help you run one - link to services
- Workshops: /events/workshops/

**Comment by rufuspollock** [comment]
I believe @beatricemartini is now dealing with this.

**Comment by smth** [comment]
Yes, as am I. @beatricemartini assigned.

**Comment by LaurieJ** [comment]
I think this is basically done for now, although i'm sure enhancements could be made. Thanks @beatricemartini !
