### ISSUE TITLE
(robots.txt) : Prevent Google from crawling notebook.okfn.org

### ISSUE THREAD

**Issue by teajaymars** [okfn/okfn.org#54]
We want notebook posts to become less prevelant. They've been removed from planet.okfn.org and the system-wide activity feed. However, for many people a Google search of their name produces their notebook posts, which are informal and not really what we want to appear.

We could do this if it were possible to customise `robots.txt`. See:

http://notebook.okfn.org/robots.txt

```
User-agent: *
Disallow: /wp-admin/
Disallow: /wp-includes/
```

Can we make it so that the file is different on different sites? I have not investigated _how_ to do this, but there must be a way. So http://okfn.org/robots.txt should be unchanged, but the notebook.okfn.org one should read:

```
User-agent: *
Disallow: *
```

**Comment by rufuspollock** [comment]
Just to check: we're not implementing this and I'm not sure we reached agreement.

Personally, I want google to crawl notebook.okfn.org :-) (it's useful and I find things there that way etc) so I'd be a strong -1 on putting this in.

**Comment by teajaymars** [comment]
Then change the user-agent to the Google robot rather than disallowing all. (Or ignore `robots.txt` in your personal scraper).

Do I need to go back to the next committee meeting and get everybody's approval before solving their problems? Surely this is a better solution than having everybody uncomfortable with the Notebook system and either (a) posting very little or (b) switching to a private system. There would be nothing for you to scrape.

**Comment by rufuspollock** [comment]
That wasn't how I understood the discussion. Let's not implement anything before this is revisited and we have a clear steer ....

**Comment by rufuspollock** [comment]
WONTFIX.
