### ISSUE TITLE
Switch to disqus comments for blog.okfn.org (?)

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#55]
Why?
- Better spam moderation
- Richer commenting system

NB: I don't think this is urgent and I'd say that at this point this is very much a discussion issue not an implementation issue.

**Comment by smth** [comment]
Could you share your reasoning behind this?

I'm going to call this a dev issue and assign @zephod :p

**Comment by smth** [comment]
I didn't see your reply (don't get notifications when someone updates the issue description). If we decide to go for this, it seems disqus has a nice plugin for it (http://wordpress.org/extend/plugins/disqus-comment-system/), which I could implement.

**Comment by rdonovan** [comment]
@mintcanary this item is on my list also. We are going to trial that plugin on blog.okfn. I'll set that up in the next 1-2 days.

**Comment by rdonovan** [comment]
This is done.

**Comment by smth** [comment]
Excellent. Closing.
