### ISSUE TITLE
Better projects page

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#6]
- Block of flagship projects (CKAN, Open Spending, School of Data, TEXTUS, Public Domain Review , Open Definition, Open Shakespeare) - almost done
- Labs Projects (ReclineJS, PyBossa, AnnotateIt)
- All Projects

See also #23
## Not doing

Need a nicer and better projects page.
- Create sections - Government, Digital Humanities, Data Tools, Cool Stuff
- Create a project page for each project

Get each project lead to update their project as part of monthly/quarterly reporting.

**Comment by lauranewman** [comment]
NB: remove unnecessary photos as part of clean-up.

**Comment by ghost** [comment]
See: http://okfnpad.org/website-sprint for sections and comments

**Comment by noelmas** [comment]
Implement carousel with flagship projects (CKAN, Open Spending, School of Data, TEXTUS)
Left hand column below other projects we want to highlight (Public Domain Review, Open Definition, Open Shakespeare)
Bottom of left hand side clicks through to "All Projects" page
Right hand column below Labs projects (ReclineJS, PyBossa, AnnotateIt)
Bottom of right hand side clicks through to "Labs"

**Comment by smth** [comment]
This is how I see this working.
https://github.com/okfn/okfn.org/raw/master/designs/okfn_07_projects_01.jpg
What do you think?

**Comment by rufuspollock** [comment]
I like this. Are we then having a separate page for "all" projects?

**Comment by smth** [comment]
Yes. The idea is that the 'More' link would go to the archive page that you requested. Where as the Labs link would go to the labs site.

**Comment by smth** [comment]
Implemented as design. Archive page is currently the old Projects page, this may need adding to.
