### ISSUE TITLE
Make the full area for "Introducing the Open Knowledge Foundation" and "What is Open Data clickable"

### ISSUE THREAD

**Issue by noelmas** [okfn/okfn.org#62]
Currently you can only click on titles full boxes need to be clickable. Same should really be applied to the blog posts below.

**Comment by smth** [comment]
Currently you can only click on the 'More' link.. I think adding links to the titles is a good idea, not sure about the whole block of text though. This may appear like we are trying to dupe people.

**Comment by smth** [comment]
Links added to headings.
