### ISSUE TITLE
Redesign of okfn.org/local

### ISSUE THREAD

**Issue by keyboardkat** [okfn/okfn.org#64]
We (quite urgently) need to redesign the current 'OKFN Chapters, Groups and Meetups' page to reflect the new 'OKFN Global Communities Network' scheme based on the strategic plan being drafted for this network in autumn 2012. 

Full details of what is needed (including a Balsamiq mockup) are found on the Google Doc here: https://docs.google.com/document/d/1Si30LvVENoiCqsChG8qmroqC82YZMNXAQnY9Bi_plHU/edit#

Highlights: 
- okfn.org/chapters to be changed to okfn.org/global
- a clearer page that serves as a hub for _all_ of our global activities, from city meetups to national groups and ambassadors to national chapters
- a place where casual and interested end-users can access more information (and application forms) to get involved
- a clear visualisation of our meetup events internationally and of our groups/chapters globally

The sooner this can be done the better, because due to bad UX from the last http://okfn.org/chapters version, the page currently serves as a mere placeholder until the new look is in place. 

Thanks very much in advance :)

**Comment by smth** [comment]
First obstacle I see is the map; if we want it to be dynamic (which I guess we do) we will need to come up with a new plan: From meetups forum "I'm afraid that we no longer support the embedding of dynamic maps of Meetup Groups on external websites."

**Comment by noelmas** [comment]
Do they have an API on which we could build our own map of Meetups?

**Comment by smth** [comment]
They do at least have an API http://www.meetup.com/meetup_api/

**Comment by noelmas** [comment]
Cheers Sam - could you give us a time estimate for yourself and Tom Rees to complete the work necessary to do our own dynamic map of the meet-ups?

**Comment by smth** [comment]
@zephod could you have a look at this when you get a chance?

**Comment by keyboardkat** [comment]
@mintcanary @zephod can one of you please give me more permissions on this repo so i can assign and add labels to Issues on the OKF site? my status has been removed somehow and I had to ask @noelmas to assign this for me... thanks in advance. 

re: the maps API, would be great if you, @mintcanary, could start on the rest of page regardless (the page is currently just a shell, so would be great to get content up again). @zephod  @mintcanary what about integrating the Meetup API with Leaflet (which provides the interactive map backend for embed?) http://leaflet.cloudmade.com/

**Comment by smth** [comment]
@keyboardkat I think you should have full permissions now.

Ok, I should be able to start on this later today / tomorrow.

**Comment by keyboardkat** [comment]
@mintcanary yep, i do now. thanks! looking forward to it :)

**Comment by smth** [comment]
Here is a quite literal interpretation of the wireframe https://raw.github.com/okfn/okfn.org/master/designs/okfn_08_global_01.jpg

I was thinking though, as all the information on the page is geographical, perhaps it should all appear on one large map?

**Comment by keyboardkat** [comment]
@mintcanary that looks great! and if you _could_ put everything on the map (ie maybe national groups/chapters in red, events in blue) that would be amazing. Have also realised since doing the mock-up that it'd actually be better to put National Groups, Chapters and Ambassadors all in the same place (rather than Chapters being above and separate from groups). I can put the status of the group in the title (this way it'll look more organised). 

Make sense? Thanks for wireframe, is perfect.

**Comment by smth** [comment]
Yeah, it seems to me that if we are going to build a map for one list of places, we might as well include the others too. I also meant though that the lists were incorporated into the map, something like this https://raw.github.com/okfn/okfn.org/master/designs/okfn_08_global_02.jpg

**Comment by keyboardkat** [comment]
@mintcanary if that is possible code-wise, that would be ultra amazing. perhaps using some of the work from the Dashboard but applying it only to local/national communities? 

:)

**Comment by smth** [comment]
I'm sure it'd be possible in the hands of a developer. I was wondering if one of our existing tools could be used.

**Comment by teajaymars** [comment]
Hey guys, I've had a little crack at extracting this data via the Meetup.com API, and once you've worked out that the OKFN's "`container_id`" is `14142` then it's really useful. They provide a really good interactive console for trying this kind of thing out: http://www.meetup.com/meetup_api/console/?path=/ew/communities

I've booted a Github repo with some Python code for playing around with this data. I think it should be rolled into the Activity API :-) For now, it lives here: https://github.com/okfn/meetup-mashup

The spreadsheet containing a one-off snapshot of events around the world lives here: https://docs.google.com/spreadsheet/ccc?key=0Au6XVBWIk_RndHJ0Vk1VRnQtT19CYTh0LWlKX1ZKYUE#gid=0

Sam, I hope this might get you started with a bit of data wrangling, perhaps some Google Fusion Tables etc, to produce a map something like the one mocked up above?

**Comment by smth** [comment]
Have just put that spreadsheet into Fusion Tables (looks like a nice tool) to see what I can do with it. Something to think about; do we want to show all the events on the map (as that current spreadsheet contains)? This will give multiple markers in any location with more than one event coming up. Or do we just show the locations, as I believe the Meetup map does?

**Comment by smth** [comment]
Ok, so I've made this map http://okfnlabs.org/okfn.org/fusion-1.html
It could show chapters, groups and ambassadors as different gradients of green, these would be taken from one spreadsheet. On top of that it shows pending meetups, according to Toms spreadsheet above.
It needs some beautifying, but what do we think in principle?

This is currently using Fusion tables (though not really fusing much) and Google Maps API. Rufus has expressed a desire for this to use Recline instead.

**Comment by keyboardkat** [comment]
@mintcanary that map looks great - if there's a way to do those 3 shades - or even diff colours - (ie, one for National Chapters, one for National Groups, and one for Local Ambassadors/Meetups) that'd be even more amazing!

I'd be happy if this was used for now on the site, so we can get the page up and running for http://okfn.org/local [ie so we no longer have to see that sad and outdated http://okfn.org/chapters page again!] and move to Recline if/when there's time. 

:)

**Comment by smth** [comment]
You can do three shade of green, currently requires maintaining a separate column with a number 1-3 (could possibly automate this..)
That sounds like a good plan, I'll get on it this week.

**Comment by smth** [comment]
@keyboardkat I have shared the map spreadsheet with you and added a map to http://okfn.org/local/ so you can have a play with it. I have noticed though that the coloured tiles can get cached for a long time, so changes may take a while to appear on the map. You may see some polygons as red, even if you have correctly added a number from 1 to 3 (as mentioned above), this is because it is the default colour and the table hasn't updated the map yet. I'm guessing in the long term this won't be too much of an issue, but we'll have to see how you get on.

**Comment by keyboardkat** [comment]
Great @mintcanary - thanks for this. Unfortunately when I go to okfn.org/local instead of the map tho, I get "Error 101 (net::ERR_CONNECTION_RESET): The connection was reset". :(

**Comment by smth** [comment]
Hmm I can't replicate this. A quick search threw up this https://productforums.google.com/forum/?fromgroups=#!topic/chrome/uASReL5OxPk

**Comment by keyboardkat** [comment]
@mintcanary have also now gotten emails from some local community members who are confused by map - would you mind taking it down for now, and we can work on it later in next few weeks again when we both have time to? I love how it looks - (working now!) - but we'll have to modify it more before it can go public. w00t.

**Comment by smth** [comment]
Ok, I have removed the map. I didn't realise we were now linking to that page to be honest.

**Comment by rufuspollock** [comment]
INVALID. out of date - see instead #75.
