### ISSUE TITLE
Mail Chimp sign up box on front page and elsewhere on website

### ISSUE THREAD

**Issue by noelmas** [okfn/okfn.org#66]
Set up Mail Chimp sign up page and replace existing OKFN Annoucne sign up boxes with Mail Chimp sign up

**Comment by smth** [comment]
Done

**Comment by noelmas** [comment]
Great - can we try it out on the top?

**Comment by noelmas** [comment]
@rgrp  mailing list has now been switched over on main site - please migrate OKFN announce

**Comment by smth** [comment]
Try it out as in see what it looks like, or implement to test it?

**Comment by noelmas** [comment]
Let's just implement it, it needs to be one of the first things people see...

**Comment by smth** [comment]
Ok.. have moved to above header.
