### ISSUE TITLE
Make carousel move automatically

### ISSUE THREAD

**Issue by noelmas** [okfn/okfn.org#68]
Currently too static, should flick through automatically, users won't know that they have to click

**Comment by smth** [comment]
I agree that most people will not navigate through the slides, there are however lots of arguments against automatic carousels. See http://conversionxl.com/dont-use-automatic-image-sliders-or-carousels-ignore-the-fad/

**Comment by noelmas** [comment]
This is interesting stuff and would have been good to look at before we decided to implement a carousel. Having said that now we have one with lots of important stuff on it that no one looks at I think we should make it move automatically. It's also important to bear in mind that lots of funders want to check our home page to see that the activities they fund are mentioned...

**Comment by smth** [comment]
Although the carousel was added before I came on board, I don't have a problem with static carousels. I liken it to designing a magazine. You want to put all the important stuff on the cover, some people might flick through, so it doesn't hurt to have some more captivating stuff inside, just remember you can't rely on people flicking through. Automatically sliding (I guess this is where the analogy falls down slightly) is like the magazine tuning its own pages on the shelf, less engaging, more difficult to see what you want and a bit annoying.

Having said that.. I have now made the carousel automatically slide :)
