### ISSUE TITLE
Square version of ckan logo and a larger one

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#73]
2 requests:
- Square version of this http://assets.okfn.org/p/ckan/img/ckan-logo.png - could we just have the square but with CKAN text inside the white triangle (like http://assets.okfn.org/p/ckan/img/ckan_logo_box.png but with new box you have done)
- Can we get larger png versions (somewhere in range 250px to 500px wide) - I don't mind if these are new defaults and replace old ones or are new

**Comment by smth** [comment]
Both of those have now been replaced:

http://assets.okfn.org/p/ckan/img/ckan_logo_box.png
http://assets.okfn.org/p/ckan/img/ckan-logo.png

**Comment by rufuspollock** [comment]
I don't want the asymmetric one as square though. I wanted it like the new one because it is so much nicer :-) (I cited the old one as an example ...)

**Comment by smth** [comment]
It is the new one.. maybe you need to refresh your browser?

**Comment by rufuspollock** [comment]
Ah sorry!! Looks great!
