### ISSUE TITLE
Improvements to 'Join OKFN Mailing List' on OKFN.org homepage

### ISSUE THREAD

**Issue by keyboardkat** [okfn/okfn.org#74]
Please change so this says "Join Us" instead.

Also change so 'Name' is one field and 'Location' is the other field.

[note: this is from Rufus and Kat at C4CC] :)

**Comment by smth** [comment]
What is the thinking behind combining the first and last name fields? It might be nice to retain this separation when it comes to sending out campaigns.

A few thoughts on location field:
- MailChimp does record location automatically I believe, there is obviously a question of accuracy with this however
- For this information to be useful I guess we need everyone entering this at the same level, for example if some people enter country name and others city name it's going to be difficult to reconcile. So we either need to be more specific with the labelling, or perhaps better than that make it a dropdown. What was the desire here, to get the country?

**Comment by keyboardkat** [comment]
cc @rgrp @noelmas - does it record location for each person? essentially, we wanted to know whether we could get people to sign up to mailchimp/announce while also gathering useful info about them (ie, background and location)... :)

**Comment by smth** [comment]
Yes, it records geodata of every (new) subscription. Because MailChimp know this is geodata it can very easily be used as such, for example to send an email to everyone within so many miles of a town.

**Comment by rufuspollock** [comment]
@mintcanary combining the fields: not a big deal but just a cleaner 2 fields interface (and i guess we could use space for something else)

Rather than "Join Us" I'd say go for: **"Get updates"** (key thing though is to remove "OKFN mailing list" - most people will want to get news but will not want to sign up to a mailing list for an acronym they may not recognize)

**Comment by keyboardkat** [comment]
@mintcanary @rgrp i'd still think that getting some sort of personal info from these people (since we won't interact with them directly once they join this list) would be ideal - ie, what is their background? why are they interested?

I believe Sam @noelmas had ideas about what the title of the overall list should be - I'm not sure if get updates would be descriptive enough without any other information provided... but maybe that is best.

**Comment by noelmas** [comment]
Hi - I am very much a -1 to changing this to "Get updates" everything we've been working on including the Comms Plans now being circulated have OKFN Announce as the first point of entry into the OKFN community. "Get updates" is also seriously uncompelling as a call. Look at what a group like Aavaz does with their mailing list and the language they use...

**Comment by rufuspollock** [comment]
@noelmas "Join the OKFN mailing list" is also seriously uncompelling :-) - this isn't really a call either - we are asking people to subscribe to a mailing list not take action (we are talking about the main page here not other places on the site ...).

Perhaps it would be easier to discuss this in person in the near future :-)

**Comment by keyboardkat** [comment]
... looking at homepages for both Avaaz and the Code for America Brigade (both of which have great front-end language and UX, as we've already agreed!) the messaging is indeed "Join Us" not "Get Updates". 

I think @rgrp's point here was that including "mailing list" in the messaging is not what we'd like people to think about. We want them to feel they're joining a movement, not signing up for another list. Am I correct in this assumption, @rgrp @noelmas? :)

**Comment by smth** [comment]
Looks like we've done what we are going to here. Closing.
