### ISSUE TITLE
okfn.org/local relaunch

### ISSUE THREAD

**Issue by keyboardkat** [okfn/okfn.org#75]
Site to be entitled "Local Groups" and to display the following 3 categories. In early 2013, a new domain (local.okfn.org) to be created with more live information - but for now, this to be the main informational hub for Local Group activity.

Note: For details about each of these categories, including content, please refer to 'Page Design' chapter of the Local Groups redesign [Google Doc](https://docs.google.com/document/d/1Si30LvVENoiCqsChG8qmroqC82YZMNXAQnY9Bi_plHU/edit#).

1) Visual strapline - Short description

2) Map - "What's happening in my area?"

3) Icons - "How can I get involved?"

**Comment by keyboardkat** [comment]
@mintcanary @rgrp quick note that regarding the redesign of okfn.org/local ie https://github.com/okfn/okfn.org/issues/64, sam, it may be better for us to have a quick meeting in the next week or so regarding this as some things have changed from the original document after discussions between me+rufus - in the meantime, i'll work on putting text and content up on okfn.org/local. thanks!

**Comment by smth** [comment]
@keyboardkat, are you ready to discuss/work on this?

**Comment by keyboardkat** [comment]
Note: Adding updates about our convo on Dec 7th in a minute!

**Comment by rufuspollock** [comment]
@keyboardkat I really feel we need to get the content sorted without much design before bringing the design side (though it would be nice to see a map set up - though that can be done separately and embedded / iframed later ...)

**Comment by keyboardkat** [comment]
@rgrp Point taken - I've now added BOTH content and design notes to the Redesign [Google Doc](https://docs.google.com/document/d/1Si30LvVENoiCqsChG8qmroqC82YZMNXAQnY9Bi_plHU/edit#). @mintcanary you'll find both text and details about the content (as we discussed) under the 'Page Design' part of this doc. Thanks!
