### ISSUE TITLE
Branding and donate/support info across okfn sites (discussion)

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#77]
Seems like 2 aspects
- More info about us on every site / OKF branding link
  - http://popcorn.webmaker.org/
  - Little ribbon on openglam is lovely and could be expanded
- Support us / Support our work / Support this project
  - all better than Support OKFN (which is acronym most people won't recognize)
  - Support us could be a bit vague for the general set of websites

could integrate the 2 e.g. openglam logo wider with Open Knowledge foundation name + "Support our work" link just below (and click on main text / logo leading to pulldown)
## Other points

Think we also need the ribbon (or initial button/text) to say more - i'm not sure logo is enough (and also think we need a down arrow or similar to indicate this is clickable ...).

**Comment by smth** [comment]
I think creating something that will work across all sites is a good plan. Standardising the ribbon and using it to reveal a panel like the Mozilla example seems like a good idea to me.

**Comment by smth** [comment]
An idea of how this could look https://raw.github.com/okfn/okfn.org/master/designs/brand-panel_01.jpg

**Comment by rufuspollock** [comment]
@mintcanary like it

Also added comment in main issue about need for ribbon with more info - not absolutely sure but we need to think about it ...

**Comment by rufuspollock** [comment]
Re the JS (and images?) Do we want this to run from a central location on assets.okfn.org (at least for js).

This way, wherever we put this (and we _will_ use this on sites other than WP ones - cf wheredoesmmoneygo.org) and this way we can go upgrade without having to mess with original sites (once they have it installed)

**Comment by smth** [comment]
JS is all Bootstrap, so there is no additional code to host anywhere. CSS will be determined by the theme and theme options, so can't/shouldn't really be separated. We could perhaps put the content in assets somewhere, in an xml file or something.. The search will be powered by Wordpress, so will have to see if that will still function from a non WP site, but I don't think that will be a problem.

Edit: we should probably include some, default CSS in assets however.

How do you see this being implemented on non WP sites? A file being included, copy and paste some code?

**Comment by smth** [comment]
The Wordpress side of this is now live. Example here: http://openeconomics.net/

**Comment by smth** [comment]
Regarding more details in the ribbon, my feeling is that if anyone wants to know what it's about, they will click it. So space is probably better reserved for other content (such as nav items).

**Comment by smth** [comment]
After thinking bout it for a while, I decided the best way to make sure this can be included on any site was to put it in an iframe. This is now done, example and instruction how to implement here http://assets.okfn.org/themes/okfn/docs.html
