### ISSUE TITLE
New Thanks page

### ISSUE THREAD

**Issue by noelmas** [okfn/okfn.org#78]
We need a page to take donors to after they have successfully donated. It should look good maybe with a picture of someone holding a thank you sign or an equivalent graphic.

Copy is here

https://docs.google.com/document/d/1WH7axy1ilAKU4bKiefkN9gMgAmV-EfFX_zrR9PPM2Js/edit

Once up, I will customise PayPal so it takes you there

**Comment by smth** [comment]
Page here http://okfn.org/support/thank-you/
