### ISSUE TITLE
okfn.org/local/ spreadsheets

### ISSUE THREAD

**Issue by smth** [okfn/okfn.org#85]
New map implementation is great. However, it looks like the map and the list below it are now running from two separate spreadsheets. List JS needs to be updated to run from same doc as the map.

**Comment by smth** [comment]
@rgrp has this been fixed?

**Comment by everton137** [comment]
What is the JS? It'd be good to point it here so that other can possibly help.

**Comment by smth** [comment]
http://assets.okfn.org/p/okfn/app/local-groups/list.js

**Comment by rufuspollock** [comment]
@mintcanary i can fix now ...

**Comment by rufuspollock** [comment]
FIXED. Just pushed corrections to assets.

**Comment by rufuspollock** [comment]
@mintcanary note styling seems a bit wrong (I've tried to exactly duplicate original css classes etc but let me know if something needs correction there)

**Comment by smth** [comment]
Nice. Looking at the HTML, it looks like the .status span needs to be moved to inside the .text span.

**Comment by rufuspollock** [comment]
Fixed ...
