### ISSUE TITLE
WP plugin "share this" not working on okfn.de

### ISSUE THREAD

**Issue by ddie** [okfn/okfn.org#89]
I have a issue with share this on http://okfn.de/blog/

The menue form WP plugin "sharethis" doesn't show up: neither in the list of all posts nor in the single post view. 

I have tried changing almost all related settings but without any success. I wonder if you have any advice or if you could point me into the right direction. Thanks in advance!

**Comment by smth** [comment]
Just had a look, I'm seeing the ShareThis buttons.. Are you still having problems with this @ddie ?

**Comment by smth** [comment]
Closing, assumed fixed..
