### ISSUE TITLE
Embed group members on working group website

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#9]
Would be good if we could embed member list from http://okfn.org/groups/{...} on a working group website.

**Comment by ghost** [comment]
The wordpress widget available makes it really ugly.

**Comment by rufuspollock** [comment]
Is there even a widget available?

**Comment by rufuspollock** [comment]
Assigning to @mintcanary for quick research on existence of a relevant plugin. Please spend no more than 15-30m :-)

**Comment by smth** [comment]
Had a look, didn't find anything.
