### ISSUE TITLE
Mention more explicitly CC-by on OKFn sites

### ISSUE THREAD

**Issue by everton137** [okfn/okfn.org#92]
Repeating a 5 months old e-mail.

"I've circulated this blog post yesterday
http://openglam.org/2012/11/07/culture-must-always-be-a-commons/ and
a friend pointed out that there is no mention to the content license.
I also noticed that our main site just mention it here
http://okfn.org/terms-of-use/#what-we-do-with-your-content.

Wouldn't be better to have the CC-by license more explicitly on all pages?"

http://lists.okfn.org/pipermail/okfn-help/2012-November/002097.html

**Comment by rufuspollock** [comment]
@jpekel certainly an issue that openglam.org does not reference IP Policy or terms of use on main site.

However, on general point think best approach is to link those rather than insert license onto each site.

**Comment by smth** [comment]
I'm in the process of creating a global footer for all our sites, the contents of which will be pulled from, and maintained from a single location. As it stands, this content is the three links you can see at the bottom of this page: http://assets.okfn.org/themes/okfn/okf-footer.html Content suggestions welcome.

That pages also shows how this footer can be included in non-wordpress sites (wordpress sites will have a plugin).

**Comment by everton137** [comment]
@mintcanary a global footer is a good solution, but we have to think about the possibility of local groups websites, where it should point to pages in the local language.

**Comment by smth** [comment]
This is a good point. I wonder though, if it might make more sense to keep the pages centralised, but have multiple languages included. This seems to me like it would be the simplest to implement and maintain.

**Comment by everton137** [comment]
I think that is good. And the main page could change its language according to the browser locale, as happens, for example, at commons.wikimedia.org.

But I wonder if a local group has a different privacy policy than OKF Central, for instance. (Just pointing out possible issues.)

**Comment by everton137** [comment]
Well, then the page in that local language will have the local group policy. Duh.

**Comment by smth** [comment]
Closing. If anyone has any further suggestions for the footer, please reopen.
