### ISSUE TITLE
Add Search Bar (to home page)

### ISSUE THREAD

**Issue by smth** [okfn/okfn.org#95]
Currently, a search bar can be enabled in the theme options, however, this will not be displayed on the home page (see ckan.org).

Obvious alternative location for okfn.org seems to be the (currently under utilised #80 ) footer. @LaurieJ how do you feel about putting the new search box here?

**Comment by LaurieJ** [comment]
Search box is really needed for okfn.org at least.   Footer is not the place for this - breaks all good web ux practice rules. Standard is top right area of a page. 

Footer would be better than nothing, and might be ok as an interim solution, but I would say this is  inadequate and I expect us to solve this sort of problem in the coming few months at most - site search in a way/place where people will find it is a pretty basic expectation for our main web presence ;)

**Comment by smth** [comment]
Agreed. The problem we have is wanting _everything_ to be in that prominent position. This site in particular is very much designed by committee, so is difficult for one person to make a call as to what should take prominence.

A couple of options, given the space we have to work with at present:
- A search bar alongside the call to action buttons
- An icon in the navigation, that when click, reveals a search bar 

Other options:
- Make space in the nav bar for a search bar
- Move the newsletter signup back to the footer and add a similar bar for search (having both would look crazy and confusing).

**Comment by LaurieJ** [comment]
Move newsletter signup to footer.

Add search icon (mag glass) to right hand end of nav bar, which when clicked, makes a search bar. 

Problem solved ;)

**Comment by smth** [comment]
Icon and search added.

I'll leave the newsletter where it is for now, I don't think it's too much of a clash with this method, and presumably it was moved up there for a reason (it can easily be moved at any time).
