### ISSUE TITLE
Error when trying to add a new user at br.okfn.org: it is asking a CAPTCHA

### ISSUE THREAD

**Issue by everton137** [okfn/okfn.org#99]
When I tried, it is appearing the error message "ERROR: Please fill in the reCAPTCHA form." 

Link: http://br.okfn.org/wp-admin/user-new.php

**Comment by everton137** [comment]
It seems I have the same problem at the School of Data in Portuguese (escoladedados.org). It always is asking to fill a reCAPTCHA form when I try to create a new user that for a person that doesn't have an account at our network.

I was asking for people to register at our network so that I could add them, but it seems the link http://okfn.org/register/ was disabled. Why is that?

**Comment by everton137** [comment]
P. S. I have activated reCAPTCHA at br.okfn.org and it reduced a lot the number of spam. But it seems I cannot disable it now in the list of installed plugins.

**Comment by rdonovan** [comment]
@everton137 The global registration page is still active on http://okfn.org/register/. If you're currently logged in or have a saved session, BuddyPress blocks the registration page and redirects you to the homepage. Use an incognito window to verify.

I'm able to reproduce the Captcha issue on the new user form in the admin, I'm investigating that now.

**Comment by rdonovan** [comment]
The wp-recaptcha plugin is no longer actively maintained. Fortunately this issue only required a simple fix to the plugin code, which I've now deployed to our server. See fork [here](https://github.com/rdonovan/wp-recaptcha)

You should now be able to add users in the admin without seeing the captcha error. Please test and confirm.

**Comment by everton137** [comment]
@rdonovan, it is working in both now, br.okfn.org and escoladedados.org. Thank you very much!

And dumb me about trying the registration link whilst logged in. :/
